name: npm install test

on:
  pull_request:
  push:
    branches:
      - master
# on:
#   schedule:
#     - cron: '0 10 * * *'

jobs:
  scan:
    name: npm install --save err
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      - run: npm install
      